function Dec=FraDec(A,D,L)

% function Dec=FraDec(A,D,L)
% This function implement framelet decomposition.
% A ==== the data to be decomposed, which are in a square matrix.
% D ==== is the decomposition filter in 1D. In 2D, it is generated by tensor
% product. The filter D must be symmetric or anti-symmetric, which
% are indicated by 's' and 'a' respectively in the last cell of D.
% L ==== is the level of the decomposition.
% Dec ==== is the framlet coefficient which are in a cell.

% Written by Jian-Feng Cai.
% email: tslcaij@nus.edu.sg

[len,num] = size(A);
nD  = size(D,1);
Dec = zeros(len*nD,num);
for i=1:nD
    M1      = D(i,:);
    Dec((i-1)*len+1:i*len,:)   = ConvSymAsym(A,M1,L);
end